homework07/src/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import RegisterView

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {"next_page": reverse_lazy('accounts:login')}, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

homework07/src/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView

urlpatterns = [
    # Handle the root url.
    path('', RedirectView.as_view(url='notes/'), name='index'),

    # Accounts app
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # Notes app
    path('notes/', include('notes.urls', namespace='notes')),

    # Admin
    path('admin/', admin.site.urls),
]

homework07/src/notes/urls.py
from django.urls import path

from .views import NoteList, NoteDetail, NoteCreate, NoteUpdate, NoteDelete

app_name = 'notes'

urlpatterns = [
    path('', NoteList.as_view(), name='index'),
    path('<int:pk>/', NoteDetail.as_view(), name='detail'),
    path('new/', NoteCreate.as_view(), name='create'),
    path('<int:pk>/edit/', NoteUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', NoteDelete.as_view(), name='delete'),
]

homework07/src/accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin


class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if email is None:
            raise ValueError('User must have an email address.')
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email and password.
        """
        if password is None:
            raise ValueError('Superusers must have a password.')
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        return self.email

homework07/src/notes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()


class Note(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    owner = models.ForeignKey(User, related_name='notes', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

homework07/src/accounts/forms.py
from django import forms

from accounts.models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

homework07/src/notes/forms.py
from django import forms
from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body']

homework07/src/accounts/views.py
from django.contrib.auth import authenticate, login
from django.views.generic import FormView

from .forms import UserCreationForm


class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = '/'

    def form_valid(self, form):
        form.save()

        email = self.request.POST['email']
        password = self.request.POST['password1']

        user = authenticate(email=email, password=password)
        login(self.request, user)
        return super(RegisterView, self).form_valid(form)

homework07/src/notes/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse_lazy, reverse
from .forms import NoteForm
from .models import Note
from .mixins import NoteMixin


class NoteList(LoginRequiredMixin, ListView):
    paginate_by = 5
    template_name = 'notes/index.html'
    context_object_name = 'latest_note_list'

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user).order_by('-pub_date')


class NoteDetail(LoginRequiredMixin, DetailView):
    model = Note
    template_name = 'notes/detail.html'
    context_object_name = 'note'

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)


class NoteCreate(LoginRequiredMixin, NoteMixin, CreateView):
    form_class = NoteForm
    template_name = 'notes/form.html'
    success_url = reverse_lazy('notes:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.pub_date = timezone.now()
        return super(NoteCreate, self).form_valid(form)


class NoteUpdate(LoginRequiredMixin, NoteMixin, UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'notes/form.html'

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return reverse('notes:update', kwargs={
            'pk': self.object.pk
        })


class NoteDelete(LoginRequiredMixin, DeleteView):
    model = Note
    success_url = reverse_lazy('notes:create')

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)

homework07/src/templates/base.html
{% load staticfiles %}

<html>
  <head>
    <title>Elevennote</title>
    <link rel="stylesheet" media="all" href='{% static "bootstrap/css/bootstrap.css" %}'>
    <link rel="stylesheet" media="all" href='{% static "elevennote/main.css" %}'>
    <link rel="stylesheet" media="all" href='{% static "font-awesome/css/font-awesome.css" %}'>
    <link rel="stylesheet" type="text/css" media="screen"
          href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic|Oxygen:300,400,700" />
    <script src="{% static "elevennote/jquery.js" %}"></script>
    <script src="{% static "elevennote/main.js" %}"></script>

    {% block extra_head %}{% endblock %}
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">ElevenNote</a>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto"></ul>
          <span class="navbar-text">
            Signed in as {{ user.email }}.
            <a href="#">Profile</a> | 
            <a href="{% url 'accounts:logout' %}">Logout</a>
          </span>
        </div>
        {% endif %}
      </nav>

      <main role="main" class="container-fluid mt-4">
        {% block content %}{% endblock %}
      </main>
  </body>
</html>

homework07/src/templates/includes/form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

homework07/src/templates/notes/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ note.title }}</h1>

<p>{{ note.body }}</p>

{% endblock %}

homework07/src/templates/notes/form.html
{% extends "base.html" %}

{% block extra_head %}
{% load wysiwyg %}
{% wysiwyg_setup %}
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-4">
            <nav id="sidebar">

              <div class="new-note">
                <a href="{% url 'notes:create' %}" class="new-note btn btn-outline-dark">+ New Note</a>
              </div>

              <ul id="notes">
              {% if notes %}
                  {% for note in notes %}
                    <li data-url="{% url 'notes:update' note.id %}">
                        <div class="note-title">{{ note.title }}</div>
                        <div class="note-body">{{ note.body | safe }}</div>
                    </li>
                  {% endfor %}
                {% else %}
                  <li>No notes are available.</li>
              {% endif %}
              </ul>
            </nav>
        </div>

        <div class="col-8">

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        {% if object %}
        <form action="{% url 'notes:update' object.pk %}" method="post" accept-charset="utf-8">
        {% else %}
        <form action="{% url 'notes:create' %}" method="post" accept-charset="utf-8">
        {% endif %}

            {% csrf_token %}
            {% for field in form %}
            <p>
                {% if field.errors %}
            	<div class="alert alert-danger" role="alert">
                    {{ field.errors }}
            	</div>
                {% endif %}
                {{ field }}
            </p>
            {% endfor %}
            <input type="hidden" name="next" value="{{ next }}" />

        {% if object %}
            <input class="btn btn-outline-dark" type="submit" value="Update Note"/>
        {% else %}
            <input class="btn btn-outline-dark" type="submit" value="Create Note"/>
        {% endif %}
        </form>

        {% if object %}
        <form action="{% url 'notes:delete' object.pk %}" method="post" id="delete-note-form">
            {% csrf_token %}
            <a class="btn btn-outline-dark" id="delete-note">
                <i class="fa fa-trash" aria-hidden="true"></i>
            </a>
        </form>
        {% endif %}

        </div>
    </div>

{% wysiwyg_editor "id_body" %}

{% endblock %}

homework07/src/templates/notes/index.html
{% extends "base.html" %}

{% block content %}
{% if latest_note_list %}
    <ul>
    {% for note in latest_note_list %}
	<p>
   		<a href="{% url 'notes:update' note.id %}">{{ note.title }}</a><br/>
   		{{ note.body | safe }}
	</p>
	<hr />
    {% endfor %}
    </ul>
{% else %}
    <p>No notes are available.</p>
{% endif %}

{% if is_paginated %}
<div class="pagination">
   <span class="step-links">
       {% if page_obj.has_previous %}
           <a href="?page={{ page_obj.previous_page_number }}">previous</a>
       {% endif %}

       <span class="current">
           Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
       </span>

       {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
       {% endif %}
  </span>
</div>
{% endif %}

<a href="{% url 'notes:create' %}">Create a new note</a>

{% endblock %}